/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppLayoutRouteRouteImport } from './routes/_appLayout/route'
import { Route as AppLayoutIndexRouteImport } from './routes/_appLayout/index'

const AppLayoutRouteRoute = AppLayoutRouteRouteImport.update({
  id: '/_appLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutIndexRoute = AppLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLayoutRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_appLayout': typeof AppLayoutRouteRouteWithChildren
  '/_appLayout/': typeof AppLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/'
  id: '__root__' | '/_appLayout' | '/_appLayout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppLayoutRouteRoute: typeof AppLayoutRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_appLayout': {
      id: '/_appLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_appLayout/': {
      id: '/_appLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppLayoutIndexRouteImport
      parentRoute: typeof AppLayoutRouteRoute
    }
  }
}

interface AppLayoutRouteRouteChildren {
  AppLayoutIndexRoute: typeof AppLayoutIndexRoute
}

const AppLayoutRouteRouteChildren: AppLayoutRouteRouteChildren = {
  AppLayoutIndexRoute: AppLayoutIndexRoute,
}

const AppLayoutRouteRouteWithChildren = AppLayoutRouteRoute._addFileChildren(
  AppLayoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppLayoutRouteRoute: AppLayoutRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
