name: Publish
on:
  push:
    tags:
      - "monidb-v*"
      - "motype-v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - name: Determine package
        id: get-pkg
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          if [[ $TAG == monidb-v* ]]; then
            echo "dir=./packages/monidb" >> $GITHUB_OUTPUT
          elif [[ $TAG == motype-v* ]]; then
            echo "dir=./packages/motype" >> $GITHUB_OUTPUT
          else
            exit 1
          fi
      - name: Publish
        working-directory: ${{ steps.get-pkg.outputs.dir }}
        run: npx jsr publish --allow-slow-types
